import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    tag: "IT & Web",
    title: "Machine Learning: Intro to Python & R",
    price: 2500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968622/ecomm-assets/course-8_pkjm2o.jpg",
    rating: "4.5",
    categoryName: "Programming",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "Vue Complete Course with Javascript, HTML, CSS, BOOTSTRAP",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968621/ecomm-assets/course-7_idjwwv.jpg",
    rating: "5.0",
    categoryName: "JavaScript",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "Introduction to Web Development",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968621/ecomm-assets/course-5_a10cjy.jpg",
    rating: "5.0",
    categoryName: "Web Development",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "Become a Web Developer from Scratch",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968621/ecomm-assets/course-4_dd2erl.jpg",
    rating: "5.0",
    categoryName: "Web Development",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "Become a Certified HTML, CSS, JavaScript Web Developer",
    price: 2500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968622/ecomm-assets/course-1_pi9q9e.jpg",
    rating: "5.0",
    categoryName: "Web Development",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "The Complete 2022 Fullstack Web Developer Course",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968621/ecomm-assets/course-2_mnssso.jpg",
    rating: "5.0",
    categoryName: "Web Development",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "The Fullstack Nft Minting Website Course",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968622/ecomm-assets/course-1_pi9q9e.jpg",
    rating: "5.0",
    categoryName: "Web Development",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "GraphQL with React & Node js - Real Time Private Chat App",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968621/ecomm-assets/course-6_t3smjz.jpg",
    rating: "5.0",
    categoryName: "ReactJs",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "GraphQL with React & Node js - Real Time Private Chat App",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968622/ecomm-assets/course-1_pi9q9e.jpg",
    rating: "5.0",
    categoryName: "ReactJs",
    enrollment: "197,637 students",
  },
  {
    _id: uuid(),
    tag: "IT & Software",
    title: "Practical CSS3 Flexbox Media Queries & CSS Grid Mastery",
    price: 1500,
    img: "https://res.cloudinary.com/db9adijl0/image/upload/v1647968622/ecomm-assets/course-1_pi9q9e.jpg",
    rating: "5.0",
    categoryName: "CSS",
    enrollment: "197,637 students",
  },
];
